//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TussentijdsProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersoneelslidRol
    {
        public int PersoneelslidRolID { get; set; }
        public Nullable<int> PersoneelslidID { get; set; }
        public Nullable<int> RolID { get; set; }
    
        public virtual Personeelslid Personeelslid { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
